apiVersion: apps/v1
kind: Deployment   # only difference with ReplicaSet, but it's a different object in kubernetes, wrapping ReplicaSet and providing more features.
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end

    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 3
  selector:
    matchLabels:
      type: front-end



# Commands

# kubectl create -f deployment-definition.yml
# kubectl get deployments
# kubectl get replicaset
# kubectl get pods
# kubectl get all




